# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |global_config|

  global_config.vm.box = 'ubuntu-server-10044-x64-fusion503'
  global_config.vm.box_url = 'https://s3-us-west-1.amazonaws.com/vagaries/ubuntu-server-10044-x64-fusion503.box'

  # The APT server can be used to 
  aptserver_ip = '10.20.30.10'

  vms = {
    :aptserver => {
      :ip           => aptserver_ip,
      :ram          => '2048',
    },
    :awstools => {
      :ip           => '10.20.30.20',
      :forward_ssh  => true,
      :ram          => '4096',
      :cpus         => '4',
    },
    :metasploit => {
      :ip           => '10.20.30.30',
      :ram          => '8192',
      :cpus         => '8',
      :public_network => true,
    },
    :nopuppet => {
      :ip           => '10.20.30.50',
      :no_puppet    => true,
    },
    :nodejs => {
      :ip           => '10.20.30.60',
      :ram          => '4096',
      :cpus         => '4',
      :enable_gui   => true,
    }
  }

  def bool_to_on_off(val)
    if val
      return 'on'
    else
      return 'off'
    end
  end

  vms.each_pair do |vm_name, vm_settings|
    global_config.vm.define vm_name do |config|

      ###########
      # Params  #
      ###########
      ram            = vm_settings.fetch(:ram,            '2048')
      cpus           = vm_settings.fetch(:cpus,           '2')
      enable_gui     = vm_settings.fetch(:enable_gui,     false)
      enable_usb     = vm_settings.fetch(:enable_usb,     false)
      forward_ssh    = vm_settings.fetch(:forward_ssh,    false)
      no_puppet      = vm_settings.fetch(:no_puppet,      false)
      debug          = vm_settings.fetch(:debug,          false)
      public_network = vm_settings.fetch(:public_network, false)

      config.ssh.forward_agent  = forward_ssh
      config.vm.hostname        = vm_name

      if public_network
        config.vm.network :public_network
        config.vm.network :forwarded_port, guest: 8000, host: 8008
      else
        config.vm.network :private_network, ip: vm_settings[:ip]
      end

      ###############
      # VirtualBox  #
      ###############
      config.vm.provider :virtualbox do |vb|
        vb.gui = enable_gui

        vb.customize [
          'modifyvm',     :id,
          '--memory',     ram,
          '--cpus',       cpus,
          '--acpi',       'on',
          '--hwvirtex',   'on',
          '--largepages', 'on',
          '--audio',      'none',
          '--usb',        bool_to_on_off(enable_usb)]

        if enable_gui
          vb.customize [
            'modifyvm',        :id,
            '--vram',          '64',
            '--accelerate3d',  'on']
        end
      end

      ##################
      # VMWare Fusion  #
      ##################
      config.vm.provider :vmware_fusion do |vf|
        vf.gui = enable_gui

        # http://www.sanbarrow.com/vmx.html
        vf.vmx['memsize']       = ram
        vf.vmx['numvcpus']      = cpus
        vf.vmx['usb.present']   = enable_usb
        vf.vmx['sound.present'] = false
        vf.vmx['displayName']   = vm_name
      end

      ###########
      # Puppet  #
      ###########
      if ! no_puppet
        config.vm.provision :puppet do |puppet|
          puppet.module_path    = '../../modules'
          puppet.manifests_path = '../../manifests'
          puppet.manifest_file  = "#{vm_name}.pp"
          puppet.hiera_config_path = '/vms/hiera.yaml'
          puppet.working_directory = '/vms/hieradata'
          if debug
            puppet.options = "--verbose --debug"
          end
        end
      end

    end
  end
end