Vagrant.configure("2") do |config|
  ##################
  # Ubuntu 10.04.4 #
  ##################
  #config.vm.define "ubuntu-server-10044-x64-fusion503" do |v|
  #  v.vm.box = "ubuntu-server-10044-x64-fusion503"
  #  v.vm.box_url = "https://s3-us-west-1.amazonaws.com/vagaries/ubuntu-server-10044-x64-fusion503.box"
  #  v.vm.synced_folder ".", "/vagrant"
  #end

  ##################
  # Kali 1.0.3     #
  ##################
  #config.vm.define "kali-10-x64-vf503-nocm" do |v|
  #  v.vm.box = "kali-10-x64-vf503-nocm"
  #  v.vm.box_url = "https://s3-us-west-1.amazonaws.com/vagaries/kali-10-x64-vf503-nocm.box"
  #  v.vm.guest = "debian"
  #end

  cpus = '2'
  ram = '2048'

  ##################
  # Puppet Conf    #
  ##################
  config.vm.synced_folder '/vms', '/vms'

  ##################
  # VirtualBox     #
  ##################
  config.vm.provider :virtual_box do |vb|
    vb.gui = false

    # VBoxManager Reference - http://www.virtualbox.org/manual/ch08.html
    vb.customize ["modifyvm", :id,
     "--memory", ram,
     "--cpus", cpus,
     "--vram", "64",
     "--acpi", "on",
     "--hwvirtex", "on",
     "--hwvirtexexcl", "on",
     "--largepages", "on",
     "--accelerate3d", "on",
     "--usb", "off",
     "--audio", "none"]
  end

  ##################
  # VMWare Fusion  #
  ##################
  config.vm.provider :vmware_fusion do |vf|

    # By default use my favority ubuntu image
    config.vm.box = "ubuntu-server-10044-x64-fusion503"
    config.vm.box_url = "https://s3-us-west-1.amazonaws.com/vagaries/ubuntu-server-10044-x64-fusion503.box"

    vf.gui = false

    # http://www.sanbarrow.com/vmx.html
    vf.vmx["memsize"] = ram
    vf.vmx["numvcpus"] = cpus
    vf.vmx["usb.present"] = "False"
    vf.vmx["sound.present"] = "False"
  end
end