known_hosts::domain_name: eviloctopus.org
known_hosts::hosts:
    - name        : aptcache
      ip          : 192.168.1.6
      provisioner : puppet 
      ram         : 2048
    - name        : puppet
      ip          : 192.168.1.10
      provisioner : puppet 
      ram         : 2048
      debug       : true
    - name        : awstools
      ip          : 192.168.1.11
      provisioner : puppet_server
      memory      : 2048
    - name        : metasploit
      ip          : 192.168.1.12
      provisioner : puppet_server
      memory      : 8192
      cpus        : 8
    - name        : nodejs
      ip          : 192.168.1.13
      provisioner : puppet_server
      memory      : 4096
